### ISSUE TITLE
Error installing on 1.9.3p392

### ISSUE THREAD

**Issue by 29thfloor** [cldwalker/debugger#139]
I'm getting an error when running 'bundle install'. It looks like the debugger-ruby_core_source gem is supposed to fix this issue but I'm not sure it works with this Ruby version.

It also says I need to 'install development tools first' but I'm pretty sure I've done that already (ie, xcode-select --install):

'xcode-select: error: command line tools are already installed, use "Software Update" to install updates'

```
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/danielmcfarland/.rvm/rubies/ruby-1.9.3-p392/bin/ruby
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib
/Users/danielmcfarland/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

**Comment by cldwalker** [comment]
debugger-ruby_core_source has had [1.9.3-p392](https://github.com/cldwalker/debugger-ruby_core_source/tree/master/lib/debugger/ruby_core_source/ruby-1.9.3-p392) support for some time. [Googling for the last error message](https://www.google.com/search?q=ruby%20You%20have%20to%20install%20development%20tools%20first) reveals this is an with setting up gcc, not debugger specific. You should try some of the suggested solutions from [SO](http://stackoverflow.com/questions/18216865/how-to-install-command-line-tools-on-osx-mavericks) or [this issue](https://github.com/CocoaPods/CocoaPods/issues/1727).
