### ISSUE TITLE
You need to install ruby-debug to run the server in debugging mode?

### ISSUE THREAD

**Issue by dxypher** [cldwalker/debugger#85]
I'm running an app on Ruby 1.9.3p374 and Rails 3.2.13. I'm running gem install debugger in the terminal, which is successful. Then when I run rails server --debug or rails server --debugger I get the following message:

You need to install ruby-debug to run the server in debugging mode. With gems, use 'gem install ruby-debug'

When I add gem 'ruby-debug' to my Gemfile and run bundle it doesn't work with Ruby 1.9.x.

When I add gem 'ruby-debug19' to my Gemfile, run bundle and then try starting the server in debug mode, I get the same message as before:

You need to install ruby-debug to run the server in debugging mode. With gems, use 'gem install ruby-debug'

Any ideas on what I'm doing wrong?

**Comment by juansebasleal** [comment]
Nice, changing gem 'ruby-debug19' with gem 'debugger' works for me.
